name: AWS OIDC Connect
on:
  push  
permissions:
  id-token: write
  contents: read
jobs:
  SQSGuardRail:
    runs-on: self-hosted
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.ARN }}
          role-session-name: ${{ secrets.ROLENAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Print assumed role
        run: aws sts get-caller-identity

      - name: ziping lambda code
        run: |
          cd lambda_code
          zip lambda_function.zip lambda_function.py
          aws s3 cp lambda_function.zip s3://${{ vars.LambdaCodeS3Bucket }}/

      - name: Run aws CloudFormation command
        run: aws s3 cp template.yaml s3://${{ vars.LambdaCodeS3Bucket }}/ 

      - name: Run aws CloudFormation create stack set command
        run: |
          aws cloudformation create-stack-set \
            --stack-set-name MySQSGuardRailSet \
            --template-body file://template.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameters \
            ParameterKey=LambdaCodeS3Bucket,ParameterValue=${{ vars.LambdaCodeS3Bucket }} \
            ParameterKey=LambdaCodeS3Key,ParameterValue=${{ vars.LambdaCodeS3Key }} \
            ParameterKey=OrganizationalUnitId,ParameterValue=${{ vars.OrganizationalUnitIds }} \
            ParameterKey=ManagementAccountId,ParameterValue=${{ vars.ManagementAccountId }} \
            ParameterKey=AWSRegion,ParameterValue=${{ vars.AWS_REGION }} \
            ParameterKey=OrganizationId,ParameterValue=${{ vars.OrganizationId }} \
            --region ${{ vars.AWS_REGION }} \
            --permission-model SERVICE_MANAGED --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false
            
       

      - name: Run aws CloudFormation create stack instances command
        run: |
          export OPERATION_ID=$(aws cloudformation create-stack-instances \
            --stack-set-name MySQSGuardRailSet \
            --parameter-overrides \
            ParameterKey=LambdaCodeS3Bucket,ParameterValue=${{ vars.LambdaCodeS3Bucket }} \
            ParameterKey=LambdaCodeS3Key,ParameterValue=${{ vars.LambdaCodeS3Key }} \
            ParameterKey=OrganizationalUnitId,ParameterValue=${{ vars.OrganizationalUnitIds }} \
            ParameterKey=ManagementAccountId,ParameterValue=${{ vars.ManagementAccountId }} \
            ParameterKey=AWSRegion,ParameterValue=${{ vars.AWS_REGION }} \
            ParameterKey=OrganizationId,ParameterValue=${{ vars.OrganizationId }} \
            --deployment-targets OrganizationalUnitIds=${{ vars.OrganizationalUnitIds }} \
            --regions ${{ vars.AWS_REGION }} \
            --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 --output text --query OperationId)
          echo "OPERATION_ID=$OPERATION_ID" >> $GITHUB_ENV

      - name: Check the status of Stack instances
        run: |
          while true; do
              STATUS=$(aws cloudformation describe-stack-set-operation \
          --stack-set-name MySQSGuardRailSet \
          --operation-id $OPERATION_ID \
                  --query "StackSetOperation.Status" \
                  --output text)

              echo "Current Status: $STATUS"

              if [[ "$STATUS" == "SUCCEEDED" ]]; then
                  echo "Stack set operation succeeded!"
                  break
              elif [[ "$STATUS" == "FAILED" || "$STATUS" == "STOPPED" ]]; then
                  echo "Stack set operation failed or was stopped."
                  exit 1
              fi

              # Wait for 10 seconds before checking again
              sleep 10
          done